GET http://localhost:3000/users

###

GET http://localhost:3000/users/62aaae32b563d1a7a92bac8c


###


POST http://localhost:3000/users
Content-Type: application/json

###

DELETE http://localhost:3000/users/62aaae01b563d1a7a92bac86

###

PATCH http://localhost:3000/users/62aaae34b563d1a7a92bac90
Content-Type: application/json

{
    "username": "Bawitdaba",
    "password": "superpassword"
}